---
- name: Install php5.6
  become: yes
  apt: pkg=php5.6 state=latest

- name: Install php5.6-fpm
  become: yes
  apt: pkg=php5.6-fpm state=latest

- name: Install PHP Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items: "{{ php.packages }}"
  when: php.packages is defined

- include_tasks: configure.yml
- include_tasks: pecl.yml
