---
- name: Set permissions on socket - owner
  lineinfile: "dest=/etc/php/5.6/fpm/pool.d/www.conf state=present regexp='^;?listen.owner' line='listen.owner = www-data'"

- name: Set permissions on socket - group
  lineinfile: "dest=/etc/php/5.6/fpm/pool.d/www.conf state=present regexp='^;?listen.group' line='listen.group = www-data'"

- name: Set permissions on socket - mode
  lineinfile: "dest=/etc/php/5.6/fpm/pool.d/www.conf state=present regexp='^;?listen.mode' line='listen.mode = 0660'"
  notify: restart php5.6-fpm

- name: ensure timezone is set in fpm php.ini
  lineinfile: dest=/etc/php/5.6/fpm/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'
- name: enabling opcache
  lineinfile: dest=/etc/php/5.6/fpm/php.ini
              regexp=';?opcache.enable=\d'
              line='opcache.enable=1'
- name: enabling display errors
  lineinfile: dest=/etc/php/5.6/fpm/php.ini
              regexp='display_errors = \d'
              line='display_errors = Yes'
- name: change session path
  lineinfile: dest=/etc/php/5.6/fpm/php.ini
              regexp=';?session.save_path =\d'
              line='session.save_path = /vagrant/custom_sessions'
